### PR TITLE
Make base mount points shared

### LINKED ISSUE #97: support specifying mount propagation
Currently filesystems newly mounted on the host after RootlessKit has started cannot be seen from RootlessKit namespaces.

This could be solved by supporting non-private mount propagation.

### PR DESCRIPTION
**Pull request by Zyqsempai**
Fixes #97 

Made base mount point shared.
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@AkihiroSuda Did you mean something like this?

**Comment by AkihiroSuda** [comment]
Sorry, I was talking about the rootfs.

e.g.
* Run `rootlesskit bash`
* Mount `/media/cdrom` as the real root
* The files under `/media/cdrom` is invisible in the rootlesskit shell.
  The files should be visible when `rootlesskit` was launched with some flag like `--propagation=rslave`.

**Comment by Zyqsempai** [comment]
@AkihiroSuda Ok, let's summarize a little bit:
1) We need new flag for  `rootlesskit` `--propagation`
2) Possible values for flag: `slave, rslave, shared. rshared, private`
3) Based on flag value we should define mount propagation type, the only question I have, which point we should mount?

**Comment by AkihiroSuda** [comment]
https://github.com/karelzak/util-linux/blob/dc30fd4383e57a0440cdb0e16ba5c4336a43b290/sys-utils/unshare.c#L161-L168

**Comment by Zyqsempai** [comment]
@AkihiroSuda PTAL

**Comment by Zyqsempai** [comment]
@AkihiroSuda Yep, looks like, but I don't see where can be the problem.
```
findmnt -o TARGET,PROPAGATION
TARGET                                PROPAGATION
/                                     shared
├─/dev                                shared
│ ├─/dev/pts                          shared
│ ├─/dev/shm                          shared
│ ├─/dev/hugepages                    shared
│ └─/dev/mqueue                       shared
├─/run                                shared
│ ├─/run/lock                         shared
│ └─/run/user/1000                    shared
│   ├─/run/user/1000/gvfs             shared
│   └─/run/user/1000/doc              shared
├─/sys                                shared
│ ├─/sys/kernel/security              shared
│ ├─/sys/fs/cgroup                    shared
│ │ ├─/sys/fs/cgroup/unified          shared
│ │ ├─/sys/fs/cgroup/systemd          shared
│ │ ├─/sys/fs/cgroup/cpu,cpuacct      shared
│ │ ├─/sys/fs/cgroup/hugetlb          shared
│ │ ├─/sys/fs/cgroup/pids             shared
│ │ ├─/sys/fs/cgroup/net_cls,net_prio shared
│ │ ├─/sys/fs/cgroup/blkio            shared
│ │ ├─/sys/fs/cgroup/freezer          shared
│ │ ├─/sys/fs/cgroup/memory           shared
│ │ ├─/sys/fs/cgroup/devices          shared
│ │ ├─/sys/fs/cgroup/rdma             shared
│ │ ├─/sys/fs/cgroup/perf_event       shared
│ │ └─/sys/fs/cgroup/cpuset           shared
│ ├─/sys/fs/pstore                    shared
│ ├─/sys/firmware/efi/efivars         shared
│ ├─/sys/fs/bpf                       shared
│ ├─/sys/kernel/debug                 shared
│ ├─/sys/kernel/config                shared
│ └─/sys/fs/fuse/connections          shared
├─/proc                               shared
│ └─/proc/sys/fs/binfmt_misc          shared
├─/snap/core/8213                     shared
├─/snap/gnome-logs/81                 shared
├─/snap/gtk-common-themes/1353        shared
├─/snap/core18/1288                   shared
├─/snap/gnome-calculator/544          shared
├─/snap/gnome-3-28-1804/110           shared
├─/snap/gnome-characters/367          shared
├─/snap/core/8268                     shared
├─/snap/gnome-calculator/501          shared
├─/snap/core18/1279                   shared
├─/snap/gnome-3-28-1804/71            shared
├─/snap/gnome-characters/375          shared
└─/boot/efi                           shared
```
this what I see inside the rootlesskit shell, everything is shared.
And outside
```
sudo cat /proc/28338/mountinfo 
1198 994 8:20 / / rw,relatime shared:651 - ext4 /dev/sdb4 rw,errors=remount-ro
```
again root is shared, do you have any ideas?

**Comment by AkihiroSuda** [comment]
@Zyqsempai 

This seems to work for your PR:

```diff
diff --git a/pkg/parent/parent.go b/pkg/parent/parent.go
index 6e7e61b..287032f 100644
--- a/pkg/parent/parent.go
+++ b/pkg/parent/parent.go
@@ -84,9 +84,8 @@ func Parent(opt Opt) error {
        }
        cmd := exec.Command("/proc/self/exe", os.Args[1:]...)
        cmd.SysProcAttr = &syscall.SysProcAttr{
-               Pdeathsig:    syscall.SIGKILL,
-               Cloneflags:   syscall.CLONE_NEWUSER,
-               Unshareflags: syscall.CLONE_NEWNS,
+               Pdeathsig:  syscall.SIGKILL,
+               Cloneflags: syscall.CLONE_NEWUSER | syscall.CLONE_NEWNS,
        }
        if opt.NetworkDriver != nil {
                cmd.SysProcAttr.Unshareflags |= syscall.CLONE_NEWNET
```

**Comment by AkihiroSuda** [comment]
@Zyqsempai Do you want to update this, or shall I carry?

**Comment by Zyqsempai** [comment]
@AkihiroSuda I tried your suggestion, but it looks like it's still not working, but from the opposite side, now it's always shared, and it's impossible to make it private.
I pushed it, so you can try it by your self.

**Comment by AkihiroSuda** [comment]
I will carry

**Comment by AkihiroSuda** [comment]
carried in https://github.com/rootless-containers/rootlesskit/pull/109

**Pull request closed without merging**
