### PR TITLE
unfork newuidmap/newgidmap

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
It is really weird that this PR failed while https://github.com/moby/buildkit/pull/703 and https://github.com/genuinetools/img/pull/184 passed.. Maybe because this PR is based on Ubuntu rather than Alpine?

cc @giuseppe

**Comment by AkihiroSuda** [comment]
The latest commit with `apt-get build-dep uidmap` should fix the issue

**Comment by giuseppe** [comment]
> It is really weird that this PR failed while [moby/buildkit#703](https://github.com/moby/buildkit/pull/703) and [genuinetools/img#184](https://github.com/genuinetools/img/pull/184) passed.. Maybe because this PR is based on Ubuntu rather than Alpine?

might be that `<sys/capability.h>` is not present so the new feature is not compiled in

**Comment by AkihiroSuda** [comment]
Probably yes but the previous commit already had `libcap-dev` ...

**Pull request merged**
