### PR TITLE
Switch from mount(8) to mount(2) syscall

### LINKED ISSUE #90: remove dependency on `mount` binary
https://github.com/rootless-containers/rootlesskit/blob/master/pkg/child/child.go has extra exec for `mount(8)` binary.

`mount(2)` syscall could be called directly.

### PR DESCRIPTION
**Pull request by Zyqsempai**
Fixes #90 

Switch from mount(8) to mount(2) syscall

Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Thanks, will look into next week

**Comment by Zyqsempai** [comment]
@AkihiroSuda Sure;)

**Comment by AkihiroSuda** [comment]
Seems caused a regression: https://github.com/rootless-containers/usernetes/pull/119#issuecomment-569978202

**Comment by AkihiroSuda** [comment]
https://github.com/rootless-containers/rootlesskit/pull/93 should fix the regression

**Pull request merged**
