### PR TITLE
pkg/port/socat: remove redundant sprintf

### PR DESCRIPTION
**Pull request by thaJeztah**
As discussed in https://github.com/rootless-containers/rootlesskit/pull/213/files#r575905096

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]
Thanks!

**Comment by kkash18** [comment]
#215

**Review by kkash18 — COMMENTED** [review]
#214

**Review by kkash18 — COMMENTED** [review]
#213

**Comment by thaJeztah** [comment]
👆 reported account for spam

**Comment by AkihiroSuda** [comment]
Curious, spamming for what purpose? 😛

**Comment by thaJeztah** [comment]
> Curious, spamming for what purpose? 😛

curious as well. Reported three accounts like that yesterday. I think some of those accounts are just for testing ML. Usual pattern is 

1. account is created
2. wait for some time (optional?)
3. fork N repositories
4. open and merge X bogus pull requests in own repo forks
5. start spamming

steps 1-4 probably to avoid automatic detection

**Pull request merged**
